aliases: []
creation_timestamp: 1704474747902
current_stage: None
description: null
last_updated_timestamp: 1704474747902
name: naive_model
run_id: ba5dea2e8a134d9db23ef44ba959ba66
run_link: null
source: /home/igor/mlops_4/mlflow/1/ba5dea2e8a134d9db23ef44ba959ba66/artifacts/naive_model
status: READY
status_message: null
storage_location: /home/igor/mlops_4/mlflow/1/ba5dea2e8a134d9db23ef44ba959ba66/artifacts/naive_model
user_id: null
version: 2
